package okf

import (
	"fmt"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/na0fu3y/ochakai/internal/domain"
)

// Parse is the inverse of Document: it reads an OKF concept document
// (YAML frontmatter + markdown body) into a knowledge entry, so
// `ochakai get` output round-trips through `ochakai update`. Server-owned
// keys (timestamp, created_by, verified_*) are ignored — provenance comes
// from authentication, never from the payload. The trailing "# Links"
// section rendered by Document is folded back into structured links.
func Parse(doc []byte) (*domain.Knowledge, error) {
	s := strings.TrimPrefix(string(doc), "\ufeff")
	if !strings.HasPrefix(s, "---\n") {
		return nil, fmt.Errorf("not an OKF document: missing --- frontmatter")
	}
	rest := strings.TrimPrefix(s, "---\n")
	end := strings.Index(rest, "\n---\n")
	var fmPart, body string
	switch {
	case strings.HasPrefix(rest, "---\n"): // empty frontmatter
		body = rest[len("---\n"):]
	case end >= 0:
		fmPart, body = rest[:end+1], rest[end+len("\n---\n"):]
	case strings.HasSuffix(rest, "\n---"): // document ends at the delimiter
		fmPart = rest[:len(rest)-len("---")]
	default:
		return nil, fmt.Errorf("not an OKF document: unterminated frontmatter")
	}

	var fm struct {
		Type        string         `yaml:"type"`
		ID          string         `yaml:"id"`
		Title       string         `yaml:"title"`
		Description string         `yaml:"description"`
		Tags        []string       `yaml:"tags"`
		Status      string         `yaml:"status"`
		Attrs       map[string]any `yaml:"attrs"`
	}
	if err := yaml.Unmarshal([]byte(fmPart), &fm); err != nil {
		return nil, fmt.Errorf("invalid frontmatter: %w", err)
	}
	typ, ok := typeFromOKF(fm.Type)
	if !ok {
		return nil, fmt.Errorf("unknown type %q (valid: metric, query, insight, term, table)", fm.Type)
	}

	trimmedBody, links := splitLinks(strings.TrimSpace(body))
	return &domain.Knowledge{
		Type:        typ,
		ID:          fm.ID,
		Title:       fm.Title,
		Description: fm.Description,
		Tags:        fm.Tags,
		Status:      domain.Status(fm.Status),
		Links:       links,
		Attrs:       fm.Attrs,
		Body:        trimmedBody,
	}, nil
}

// typeFromOKF accepts both the display values Document writes
// ("Golden Query") and raw ochakai types ("query").
func typeFromOKF(s string) (domain.Type, bool) {
	for typ, display := range okfType {
		if strings.EqualFold(s, display) || s == string(typ) {
			return typ, true
		}
	}
	return "", false
}

var linkLineRe = regexp.MustCompile(`^- ([^:\s]+): \[([^\]]+)\]\([^)]*\)$`)

// splitLinks strips a trailing "# Links" section (as generated by
// Document) and returns it as structured links. A section whose bullets
// don't all match the generated format is treated as ordinary body text.
func splitLinks(body string) (string, []domain.Link) {
	var start int
	switch i := strings.LastIndex(body, "\n# Links\n"); {
	case strings.HasPrefix(body, "# Links\n"):
		start = 0
	case i >= 0:
		start = i + 1
	default:
		return body, nil
	}
	var links []domain.Link
	for _, line := range strings.Split(body[start:], "\n")[1:] {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		m := linkLineRe.FindStringSubmatch(line)
		if m == nil {
			return body, nil
		}
		links = append(links, domain.Link{Rel: m[1], Target: m[2]})
	}
	if len(links) == 0 {
		return body, nil
	}
	return strings.TrimSpace(body[:start]), links
}
