package okf

import (
	"fmt"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/na0fu3y/ochakai/internal/domain"
)

// Parse is the inverse of Document: it reads an OKF concept document
// (YAML frontmatter + markdown body) into a knowledge entry, so
// `ochakai get` output round-trips through `ochakai update`. Server-owned
// keys (timestamp, created_by, verified_*) are ignored — provenance comes
// from authentication, never from the payload. The trailing "# Links"
// section rendered by Document is folded back into structured links.
func Parse(doc []byte) (*domain.Knowledge, error) {
	k, rawType, err := parseDoc(doc)
	if err != nil {
		return nil, err
	}
	if k.Type == "" {
		return nil, fmt.Errorf("cannot derive a type slug from %q (any slug works as a type; recommended: metric, query, insight, term, table)", rawType)
	}
	return k, nil
}

// parseDoc parses one OKF document, also returning the frontmatter type
// verbatim so bundle import can preserve the original spelling when the
// bundle path names the type differently. k.Type is "" when no type slug
// could be derived \u2014 the caller decides whether path context fills it in.
func parseDoc(doc []byte) (*domain.Knowledge, string, error) {
	s := strings.TrimPrefix(string(doc), "\ufeff")
	if !strings.HasPrefix(s, "---\n") {
		return nil, "", fmt.Errorf("not an OKF document: missing --- frontmatter")
	}
	rest := strings.TrimPrefix(s, "---\n")
	end := strings.Index(rest, "\n---\n")
	var fmPart, body string
	switch {
	case strings.HasPrefix(rest, "---\n"): // empty frontmatter
		body = rest[len("---\n"):]
	case end >= 0:
		fmPart, body = rest[:end+1], rest[end+len("\n---\n"):]
	case strings.HasSuffix(rest, "\n---"): // document ends at the delimiter
		fmPart = rest[:len(rest)-len("---")]
	default:
		return nil, "", fmt.Errorf("not an OKF document: unterminated frontmatter")
	}

	var fm struct {
		Type        string         `yaml:"type"`
		ID          string         `yaml:"id"`
		Title       string         `yaml:"title"`
		Description string         `yaml:"description"`
		Tags        []string       `yaml:"tags"`
		Status      string         `yaml:"status"`
		Attrs       map[string]any `yaml:"attrs"`
	}
	if err := yaml.Unmarshal([]byte(fmPart), &fm); err != nil {
		return nil, "", fmt.Errorf("invalid frontmatter: %w", err)
	}
	typ, keepSpelling := typeFromOKF(fm.Type)
	attrs := fm.Attrs
	if keepSpelling != "" {
		if attrs == nil {
			attrs = map[string]any{}
		}
		attrs[AttrOKFType] = keepSpelling
	}

	trimmedBody, links := splitLinks(strings.TrimSpace(body))
	return &domain.Knowledge{
		Type:        typ,
		ID:          fm.ID,
		Title:       fm.Title,
		Description: fm.Description,
		Tags:        fm.Tags,
		Status:      domain.Status(fm.Status),
		Links:       links,
		Attrs:       attrs,
		Body:        trimmedBody,
	}, fm.Type, nil
}

// typeFromOKF maps an OKF frontmatter type to an ochakai type. Display
// values Document writes ("Golden Query") and raw recommended types
// ("query") map to the built-ins; any other value \u2014 OKF registers no
// taxonomy \u2014 is slugified into a free type, and when the slug changed the
// spelling, the original is returned to be preserved as attrs[AttrOKFType].
// A value no slug can be derived from yields ("", "").
func typeFromOKF(s string) (typ domain.Type, keepSpelling string) {
	for t, display := range okfType {
		if strings.EqualFold(s, display) || s == string(t) {
			return t, ""
		}
	}
	slug := slugifyType(s)
	if !domain.ValidType(domain.Type(slug)) {
		return "", ""
	}
	if slug == s {
		return domain.Type(slug), ""
	}
	return domain.Type(slug), s
}

// slugifyType lowercases a free OKF type value and replaces runs of
// characters a slug segment cannot hold with "-" ("Data Contract" \u2192
// "data-contract").
func slugifyType(s string) string {
	var b strings.Builder
	pending := false
	for _, r := range strings.ToLower(strings.TrimSpace(s)) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '.', r == '_', r == '-':
			if pending && b.Len() > 0 {
				b.WriteByte('-')
			}
			pending = false
			b.WriteRune(r)
		default:
			pending = true
		}
	}
	return strings.TrimRight(b.String(), "-")
}

var linkLineRe = regexp.MustCompile(`^- ([^:\s]+): \[([^\]]+)\]\([^)]*\)$`)

// splitLinks strips a trailing "# Links" section (as generated by
// Document) and returns it as structured links. A section whose bullets
// don't all match the generated format is treated as ordinary body text.
func splitLinks(body string) (string, []domain.Link) {
	var start int
	switch i := strings.LastIndex(body, "\n# Links\n"); {
	case strings.HasPrefix(body, "# Links\n"):
		start = 0
	case i >= 0:
		start = i + 1
	default:
		return body, nil
	}
	var links []domain.Link
	for _, line := range strings.Split(body[start:], "\n")[1:] {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		m := linkLineRe.FindStringSubmatch(line)
		if m == nil {
			return body, nil
		}
		links = append(links, domain.Link{Rel: m[1], Target: m[2]})
	}
	if len(links) == 0 {
		return body, nil
	}
	return strings.TrimSpace(body[:start]), links
}
